services:
  blog:
    image: ghost:5-alpine
    restart: unless-stopped
    environment:
      url: https://blog.botdefense.online
      NODE_ENV: production
      # FORCE SQLITE SETTINGS
      database__client: sqlite3
      database__connection__filename: content/data/ghost.db
      database__useNullAsDefault: 'true'
    volumes:
      - blog-data:/var/lib/ghost/content
    networks:
      - defense-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=thesis-bot-defense_defense-net"
      - "traefik.http.routers.blog.rule=Host(`blog.botdefense.online`)"
      - "traefik.http.routers.blog.middlewares=defense@file" # <====== ENABLED defense middleware
      - "traefik.http.routers.blog.entrypoints=websecure"
      - "traefik.http.routers.blog.tls=true"
      - "traefik.http.routers.blog.tls.certresolver=letsencrypt"
      - "traefik.http.services.blog.loadbalancer.server.port=2368"
      - "traefik.http.middlewares.test-compress.compress=true"

volumes:
  blog-data: